### ISSUE TITLE
Project Report 4

### ISSUE THREAD

**Issue by TelloViz** [TelloViz/Card-Collection#78]
# Progress Report 4 -- (10/4/24-10/17/24)

## Task

**Please comment** on this post with **2-4 bullet-points** for each of the points below:
- What you've done in the previous 2 weeks.
- What roadblocks have you faced.
- What do you plan on doing in this next two weeks.

### Note:
We are getting some overlap on these reports because they have been created at inconsistent timeframes. I'm trying to get them more on schedule. We have done them every 2 weeks but they are done oftentimes mid-cycle, so it's ok if there is overlap with a prevoius report at this time.

**Comment by TelloViz** [comment]
- **Accomplished**
   - Created a presentation PowerPoint.
   - Developed program architecture and design documents:
      - `Backend` Class, `BackendController` Class, `SearchHandler` Class
      - `constructQuery` function, `requestSearch` function, `handleSearch` function
   - Implemented the BackendController Class.

- **Roadblocks**
   - None.

- **Planned**
   - Write this report.
   - Maintain project board and progress.
   - Implement functions once the group reviews the Pull Request for the `BackendController`.

**Comment by batucs** [comment]
* Accomplished
  * Implemented the class structure for the searchHandler class.
  * prototype is now able to run on linux machine, despite some initial trouble.

* Roadblocks
  * having to brush up on some git functionalities
  * program still unable to run on mac

**Comment by TelloViz** [comment]
> **Accomplished**  
>   
>   * Implemented the class structure for the `SearchHandler` class.  
>   * Prototype is now able to run on a Linux machine, despite some initial trouble.  
>   
> **Roadblocks**  
>   
>   * Brushing up on some Git functionalities.  
>   * Program still unable to run on Mac.

Thank you, @batucs.

**Some Notes:**

1) **Class skeletons:** Implementing class skeletons can be done in any text editor. None of your assigned tasks require the Qt framework or tools like Qt Creator or Qt Designer, so this should not be a roadblock at this point. Implementing one skeleton class should take no more than 10 minutes and can be done using VS Code, Visual Studio, Notepad, Notepad++, Vim, Nano, Emacs, etc. As discussed, I’ve taken on the front-end tasks involving Qt Creator, which you no longer need to worry about.

2) **Seeking help:** If you're encountering Git issues, ask for help sooner. Git is a well-documented system with plenty of resources, so it shouldn't cause delays.

3) **Pull requests:** A pull request for the `SearchHandler` class is required before marking it as "implemented." It needs to be reviewed.

4) **System issues:** These have been recurring in your progress reports for several weeks. At this stage, you should either ask for additional help or proceed with your Linux setup, which you’ve confirmed works. Mac compatibility is not necessary for your tasks, and continuing to use this as a roadblock is not acceptable.

5) **Task priorities:** Please focus on the tasks assigned to you on the project board. Working on unassigned tasks or marking tasks as completed without submitting code is not helpful.

6) **Next two weeks:** You did not specify what you plan to work on for the next two weeks. Please provide that information as requested.

**Comment by wasup-c** [comment]
Accomplished

-    Constructed Backend Class
-    Constructed all_sets Function
-    Implemented all_sets function
-    Design query_api function
-    Created Activity Diagram
-    Constructed query_api function
-    Constructed handle_search function

Roadblocks

-   Still familiarizing myself with git and VENV
-   Still trying to get QT Creator to work on MAC

Planned

**Comment by TelloViz** [comment]
> Accomplished
> 
> * Constructed Backend Class
> * Constructed all_sets Function
> * Implemented all_sets function
> * Design query_api function
> 
> Roadblocks
> 
> * Still familiarizing myself with git and VENV
> * Still trying to get QT Creator to work on MAC

Please see the notes I put above for @batucs . Some of these are relevant here as well.
