### ISSUE TITLE
Wrong Directory

### ISSUE THREAD

**Issue by TelloViz** [TelloViz/Card-Collection#90]
#  'backend.py' file is in the wrong directory.

## Correct

```md
Card-Collection/
├── CardCollection/
│   ├── backend.py
│   ├── backendcontroller.py
│   └── main.py
├── (other directories and files)
```

## Incorrect

```md
Card-Collection/
├── backend.py
├── CardCollection/
│   ├── backendcontroller.py
│   └── main.py
├── (other directories and files)
```

_Originally posted by @TelloViz in https://github.com/TelloViz/Card-Collection/issues/89#issuecomment-2415379245_

**Comment by wasup-c** [comment]
should be complete now, it was moved to correct and removed from the wrong. let me know if i still didnt do it right
